#define KEY_RELEASED 0x0
#define KEY_PLUS     0x1
#define KEY_MINUS    0x2
#define KEY_F1       0x3
#define KEY_F2       0x4
#define KEY_F3       0x5
#define KEY_F4       0x6
#define KEY_F5       0x7
#define KEY_LEFT     0x8
#define KEY_RIGHT    0x9
#define KEY_UP       0xa
#define KEY_DOWN     0xb
#define KEY_ENTER    0xc
